Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path
from . import views

app_name = 'pizzas'
		
urlpatterns = [
	path('', views.index, name='index'),
	path('pizzas', views.pizzas, name='pizzas'),
	path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
	path('new_comment/<int:pizza_id>/', views.new_comment, name = 'new_comment'),
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):

    pizza_name = models.CharField(max_length = 200)

    def __str__(self):

        return self.pizza_name

class Toppings(models.Model):

    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    topping_name = models.TextField() 

    class Meta:

        verbose_name_plural = 'toppings'

    def __str__(self):

        return self.topping_name

class Comment(models.Model):

    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    comment = models.TextField()

    class Meta:

        verbose_name_plural = 'comments'
    
    def __str__(self):

        return self.comment

pizzas/forms.py
from django import forms

from .models import *


class CommentForm(forms.ModelForm):

    class Meta:

        model = Comment
        fields = ['comment']
        labels = {'comment':''}
        widgets = {'comment': forms.Textarea(attrs={'cols':80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.
def index(request):

	"""The home page for Learning Log."""
	return render(request, 'pizzas/index.html')

def pizzas(request):

    pizzas = Pizza.objects.order_by('pizza_name')

    context = {'p':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):

    p = Pizza.objects.get(id = pizza_id)
    toppings = Toppings.objects.filter(pizza = p)
    comments = Comment.objects.filter(pizza = p)

    context = {'pizza':p, 'toppings':toppings, 'comments':comments}

    return render(request, 'pizzas/pizza.html', context)

def new_comment(request, pizza_id):

    pizza = Pizza.objects.get(id = pizza_id)

    if request.method != 'POST':

        form = CommentForm()

    else:

        print(request.POST)
        form = CommentForm(data = request.POST)

        if form.is_valid():

            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id = pizza_id)

    context = {'form':form, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/base.html
<p> 
    <a href = "{% url 'pizzas:index' %}"> Pizzeria </a>
    <a href = "{% url 'pizzas:pizzas' %}"> Pizzas </a>
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizzeria </p>

<p> Welcome to Alden's Pizzeria!</p>

<p>Use the "Pizzas" link above to view our delicious pizzas!</p>

<body>
    <img alt="Pizza" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJ9A-GY7sfKej8eg6etm1krxBMWke0pm_vbQ&usqp=CAU">
</body>
{% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href ="{% url 'pizzas:pizza' pizza.id %}" >{{pizza}}</a></p>

<p>Add a new comment:</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method = "post">

    {% csrf_token %}

    {{ form.as_p }}

    <button name="submit">Add comment</button>

</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizza: {{ pizza }}</p>

<ul>
    {% for t in toppings %}
    <li>{{ t.topping_name }}</li>
    
    {% empty %}
    <li>No toppings for this pizza have been added yet.</li>
    {% endfor %}
</ul>


<a href="{% url 'pizzas:new_comment' pizza.id %}">Add a new comment</a>

<ul>
    {% for c in comments %}
    <li>{{ c.comment }}</li>

    {% empty %}
    <li>No comments for this pizza have been added yet.</li>
    {% endfor %}
</ul>

<body>
    <img alt="Pizza" src=https://www.budgetbytes.com/wp-content/uploads/2020/06/BBQ-Chicken-Pizza-one-slice.jpg>
    <img alt="Pizza" src=https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F19%2F2014%2F07%2F10%2Fpepperoni-pizza-ck-x.jpg&q=60>
</body>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in p %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}"> {{ pizza.pizza_name }} </a>
        </li>

    {% empty %}
    <li>No pizza has been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}